core_obs_categories = {"Gasses/Flammables/Combustibles": 1,
                       "Competent Person": 2,
                       "Confined Space": 3,
                       "Cranes/Rigging/Inspections": 4,
                       "IDLH (Immediately Dangerous to Life or Health)": 5,
                       "Electrical Safety - Low Voltage": 6,
                       "Electrical Safety - High Voltage": 7,
                       "Stormwater Pollution Prevention": 8,
                       "Excavations": 9,
                       "Fall Protection": 10,
                       "Fire Protection": 11,
                       "First Aid": 12,
                       "Floor Holes": 13,
                       "Forklifts/Elevating Platgorms/Aerial Devices": 14,
                       "Guardrails/Toe boards": 15,
                       "HazCom": 16,
                       "Heavy Construction Equipment": 17,
                       "Heat Illness Prevention": 18,
                       "Hot Work/Welding": 19,
                       "Housekeeping": 20,
                       "Ladders": 21,
                       "Material Handling": 22,
                       "PPE": 23,
                       "Posting Requirements": 24,
                       "Respiratory Protection/Use/Storage": 25,
                       "Scaffolding": 26,
                       "Struck By/Caught In/Caught Between": 27,
                       "Tools and Equipment": 28,
                       "Traffic Control": 29,
                       "Training": 30,
                       "Health Hazards": 31,
                       "Impalement Hazard": 32,
                       "Machine Guarding": 33,
                       "Access and Egress": 34,
                       "Lighting": 35,
                       "Lockout/Tagout": 36,
                       "Toilets/Sanitation": 37,
                       "Tunnels and Tunneling": 38}

facebook_obs_categories = {"Abrasive Blasting": 1,
                         "Air and Powder Actuated Tools": 3,
                         "Air Compressors": 4,
                         "Barricades/Access Control": 5,
                         "Body/Working Position (Ergonomics)": 6,
                            "Caught In-Between": 7,
                            "Chemical Hazard": 8,
                            "Commissioning Activity": 9,
                            "Concrete Pumping": 10,
                            "Confined Space": 11,
                            "Covid Communication": 12,
                            "Covid PPE": 13,
                            "Covid Safe Distancing": 14,
                            "Covid Safe Entry and Screening": 15,
                            "Covid Sanitation": 16,
                            "Covid Transportation": 17,
                            "Covid Work Arrangement": 18,
                            "Covid Workforce Zoning": 19,
                            "Cranes and Boom Trucks": 20,
                            "Creature Hazard": 21,
                            "Cut/Laceration Hazard": 71,
                            "Documentation": 22,
                            "Electrical Hazard": 23,
                            "Electrical Tools and Cords": 24,
                            "Emergency Access or Egress": 25,
                            "Emergency Response or Employee Care Related": 26,
                            "Environmental Hazard": 27,
                            "Excavations": 29,
                            "Fall Protection": 30,
                            "Falling Object Protection": 31,
                            "Hot Work/Fire Protection": 32,
                            "Forklifts": 33,
                            "Fuel and Chemical Storage": 34,
                            "GHS/HAZCOM": 35,
                            "Hand Safety/positioning": 72,
                            "Hand Tools": 36,
                            "Heat Stress": 37,
                            "Heavy Equipment": 38,
                            "Housekeeping": 40,
                            "Human Factor-Behaviours": 42,
                            "Impalement Hazard": 43,
                            "Industrial Hygiene (Noise/Air)": 44,
                            "Ladders and Stairways": 45,
                            "Lighting": 46,
                            "Lockout/Tag Out": 47,
                            "Machine Guarding": 48,
                            "Material Handling": 49,
                            "Material Storage": 50,
                            "Mobile Elevating Work Platform": 2,
                            "Mobile Plant": 51,
                            "New Hire Program": 52,
                            "Overhead Work": 53,
                            "Personal Protective Equipment": 54,
                            "Pinch Point Hazard": 55,
                            "Puncture Hazard": 56,
                            "Regulatory Postings and Signage": 57,
                            "Rigging Materials and Methods": 58,
                            "Sanitation (Health)": 59,
                            "Scaffolds and Temporary Work Platforms": 60,
                            "Security": 61,
                            "Signage": 62,
                            "Struck By": 63,
                            "Temporary Power": 64,
                            "Temperature": 65,
                            "Trade Damage": 66,
                            "Traffic or Pedestrian Controls": 67,
                            "Walking and Working Surfaces": 68,
                            "Welding and Cutting": 69,
                            "Wellness and Wellbeing": 70}

facebook_obs_buildings = {"Building 1": 1,
                          "Building 2": 2,
                          "Building 3": 3,
                          "Building 4": 4,
                          "Building 5": 5,
                          "Building 6": 6,
                          "Building 7": 7,
                          "Administration Building": 13,
                          "Batch Plants": 12,
                          "Construction Locations": 8,
                          "Entrance": 9,
                          "Ibos": 10,
                          "Main Building": 16,
                          "Offsite Facility": 14,
                          "PEMB/Construction Offices": 11,
                          "Site Office": 17,
                          "TOL 1/Plot 1 Carpark": 18,
                          "TOL 2": 19,
                          "Worker Experience Yard": 15}

facebook_obs_areas = {"A": 1,
                      "B": 2,
                      "C": 3,
                      "D": 4,
                      "Admin (F)": 6,
                      "Core (E)": 5,
                        "Conveyance Pipe - Cole Road": 23,
                        "Conveyance Pipe - Curtis Road": 24,
                        "Conveyance Pipe - Kuna Mora Road": 25,
                        "Employee Parking": 14,
                        "Gantry": 18,
                        "Generator Yard": 9,
                        "Influent Lift Station": 26,
                        "Infrastructure": 21,
                        "KE01": 27,
                        "KE02": 28,
                        "KE03": 29,
                        "Lagoons": 30,
                        "Laydown": 10,
                        "Lunch Area": 11,
                        "NCB": 31,
                        "North 40": 32,
                        "Offices": 12,
                        "Operations Yard": 33,
                        "Phase 1B": 34,
                        "Phase 1C": 35,
                        "Restroom": 13,
                        "Roof": 22,
                        "SGA 1 (Level 9/10)": 15,
                        "Site": 7,
                        "Site Substation": 36}

facebook_obs_levels = {"Underground": 1,
                       "Ground": 2,
                       "Penthouse": 3,
                       "Roof": 4,
                       "1": 11,
                       "2": 12,
                       "3": 13,
                       "4": 14,
                       "5": 15,
                       "6": 16,
                       "7": 17,
                       "8": 18,
                       "9": 19,
                       "20": 10,
                       "21": 11,
                       "Northeast Gantry": 22,
                       "Northwest Gantry": 23,
                       "Southeast Gantry": 24,
                       "Southwest Gantry": 25}

facebook_obs_rooms = {"Coil Damper Room": 11,
                      "Coil Room": 12,
                      "Core Wall 1": 44,
                      "Core Wall 2": 45,
                      "Core Wall 3": 46,
                      "Core Wall 4": 47,
                      "Core Wall 5": 48,
                      "Core Wall 6": 49,
                      "Core Wall 7": 50,
                      "Core Wall 8": 51,
                      "Core Wall 9": 52,
                      "Core Wall 10": 53,
                      "Core Wall 11": 54,
                      "Corridor": 4,
                        "Data Hall": 13,
                        "Detention Tank 1": 30,
                        "Detention Tank 2": 31,
                        "Detention Tank 3": 32,
                        "Dump Tank 1": 33,
                        "Dump Tank 2": 34,
                        "Dump Tank 3": 35,
                        "E. Coil Vestibule": 1,
                        "E. Coil Damper Vestibule": 14,
                        "E. Evaporator Vestibule": 15,
                        "E. Fan Vestibule": 16,
                        "E. Filter Vestibule": 17,
                        "Electrical Room": 10,
                        "Evaporator Room": 18,
                        "Exhaust Room": 3,
                        "Fan Room": 19,
                        "Filter Room": 9,
                        "Fuel Tank": 29,
                        "Intake Room": 20,
                        "Loading Dock": 56,
                        "MDF": 57,
                        "Network Core": 41,
                        "North Data Hall": 43,
                        "North Electrical Room": 39,
                        "Process Water Plant (Pwp)": 36,
                        "Relief Fan Room": 21,
                        "Remote - IDF": 55,
                        "South Electrical Room": 40,
                        "South Data Hall": 42,
                        "Stair 1": 22,
                        "Stair 2": 8,
                        "Storage": 6,
                        "Temporary Substation": 38,
                        "Vestibule": 7,
                        "W. Coil Damper Vestibule": 2,
                        "W. Coil Vestibule": 5,
                        "W. Evaporator Vestibule": 23,
                        "W. Fan Vestibule": 24,
                        "W. Filter Vestibule": 25,
                        "Water Treatment": 26,
                        "Water Tanks": 37,
                        "22kv Substation": 28,
                        "66kv Substation": 27}